export const products = [
    {
        id: 1,
        image: "https://i.ibb.co/f4cMwRx/2-botellas-estuche.jpg",
        product: "Box Malbec y Cabernet Sauvignon", 
        category: "Malbec, Cabernet",
        description: "Caja con una botella de Malbec y otra de Cabernet Sauvignon",
        price: 3600,
        stock: 100,
        initial: 1,
    },
    {
        id: 2,
        image: "https://i.ibb.co/drkhPhQ/cabernet-estuche.jpg",
        product: "Estuche Reserva Cabernet Sauvignon", 
        category: "Cabernet",
        description: "Caja con una botella de Cabernet Sauvignon",
        price: 2000,
        stock: 100,
        initial: 1, 
    },
    {
        id: 3,
        image: "https://i.ibb.co/3FMGLsm/malbec-estuche.jpg",
        product: "Estuche Reserva Malbec", 
        category: "Malbec",
        description: "Caja con una botella de Reserva Malbec",
        price: 2000,
        stock: 100,
        initial: 1,
    },
    {
        id: 4,
        image: "https://i.ibb.co/NYCtV6Q/cabernet-caja.jpg",
        product: "Reserva Cabernet Sauvignon x 6", 
        category: "Cabernet",
        description: "Caja con seis botellas de Cabernet Sauvignon",
        price: 8900,
        stock: 100,
        initial: 1,
    },
    {
        id: 5,
        image: "https://i.ibb.co/0r4GN1K/malbec-caja.jpg",
        product: "Reserva Malbec x 6", 
        category: "Malbec",
        description: "Caja con seis botella de Malbec",
        price: 8900,
        stock: 100,
        initial: 1,
    }
]